spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.jdbc.time_zone: UTC
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 8083