spring:
  rabbitmq:
    username: alex
    password: password
  cloud:
    stream:
      rabbit:
        binder:
          nodes: localhost:5672
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true