spring:
  application:
    name: project-service
  rabbitmq:
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    addresses: ${RABBIT_NODE}
  cloud:
    stream:
      bindings:
        taskPublisher:
          destination: task
      rabbit:
        default:
          producer:
            declare-exchange: false
            exchange-type: direct
            routing-key-expression: headers['type']
      output-bindings: taskPublisher
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.jdbc.time_zone: UTC
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 8083